# jwt_handler-provider Makefile

CAPABILITY_ID = "michaelrademeyer:jwt_handler_provider"
NAME = "jwt_handler_provider"
VENDOR = "MichaelRademeyer"
PROJECT = jwt_handler_provider
VERSION = 0.1.0
REVISION = 0

include ./provider.mk

test::
	cargo clippy --all-targets --all-features

